config/routes.rb
 Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'

  get 'dashboard', to: 'profiles#dashboard', as: :dashboard
  patch '/applications/:id/sent_application', to: 'applications#sent_application', as: :sent_application

  resources :startups, only: [ :index, :show ] do
    resources :applications, only: [ :new, :create ]
    resources :favorites, only: :create
  end


  resources :applications, only: [ :index, :show, :create, :edit, :update, :destroy ]
  resources :favorites, only: [ :index, :destroy ]
  resources :sectors, only: :index
  resources :profiles, only: [ :create, :edit, :update ]
end

app/models/application.rb
class Application < ApplicationRecord
  # code below is for the upload of the pdf document of the student
  has_one_attached :document
  belongs_to :user
  belongs_to :startup

  def content
    if read_attribute(:content).blank?
      default_content
    else
      read_attribute(:content)
    end
  end

  def default_content
    "#{Date.today.to_date.to_formatted_s(:long)}\n#{self.startup.name} \n#{self.startup.address}\nDear Madam/Sir,\n
    I’m writing to you regarding the internship role that opened up recently. I came across this internship on iStartUP platform, and was delighted to find that my academic achievements meet all of the necessary requirements. I am seeking a challenging and rewarding internship, which is why I was drawn to this exciting opportunity.\n
    During my studies, I have acquired various skills as well as an increased inquisitiveness for everything related to your company’s focus and entrepreneurship.  As part of my future studies, I’d like to explore topics in the following areas:\n
    Idea exploration and validation\n
    - Digital Marketing\n
    - Customer Survey\n
    - Fundraising\n
    - Product development\n
    I would be delighted to have an opportunity to personally interview with you. Please accept the enclosed resume and feel free to contact me at your earliest convenience.  I appreciate your time and consideration.\n
    Yours sincerely,\n
    #{self.user.first_name} #{self.user.last_name} \n#{self.user.email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # permit an extra param. This is just for the user when he signs up
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "www.istartup.digital" }
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :sent_application, :update, :destroy]

  def index
    @applications = Application.where(user_id: current_user.id)
  end

  def show; end

  def create
    @application = Application.new(application_params)
    @application.user = current_user
    redirect_to application_path(@application) if @application.save
  end

  def edit; end

  def update
    if @application.update(application_params)
      redirect_to application_path(@application)
    else
      render :edit
    end
  end

  def sent_application
    @application[:sent] = true
    redirect_to dashboard_path if @application.save
  end

  def destroy
    @applcation.destroy
  end

  def generate_pdf
    grover = Grover.new(_application_content.html.erb, format: 'A4')
    @pdf = grover.to_pdf
  end

  private

  def set_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:id, :startup_id, :user_id, :sent, :document, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_application_content.html.erb
<% text = @application.content.split("\n") %>
    <% text.each do |string| %>
      <p><%= string %></p>
    <% end %>

app/views/applications/edit.html.erb
<div class="container box-application">
<div class="container">
  <h2 style="color:#50A87C; margin-bottom: 20px; text-align: center">Personalize your application for <%= @application.startup.name %></h2>

<div style= "align-items=center">
  <div>
    <%= simple_form_for @application, url: application_path(@application), method: :patch do |f| %>
    <%= f.input :content, as: :text, input_html: { value: f.object.content, :rows => 20 }, label: false %>
    <%= f.submit "Save changes", class: "btn btn-ghost" %>
    <% end %>
  </div>
  <%= link_to "Go back", application_path(@application), class: "btn btn-outline-primary" %>
</div>
</div>
</div>

app/views/applications/show.html.erb
<div class="container box-application">
  <h1 style="color:#50A87C; text-align:center; margin-bottom: 40px;">Your application for <%= @application.startup.name %></h1>
  <p style="color:#52A87C; margin-top: -40px; text-align:center; margin-bottom: 60px;">______________________________________________________________________</p>
  <% if @application.document.attached? %>
    <div class="d-flex">
    <% end %>
      <div class="container">
        <%= render "application_content", application: @application %>
      </div>
      <div class="container">
        <% if @application.document.attached? %>
          <%= cl_image_tag(@application.document.key, width: 500, height: 700, crop: :fill) %>
        <% else %>
          <% if @application.sent == false %>
          <%= simple_form_for @application, url: application_path(@application) do |f| %>
            <%= f.input :document, input_html: { class: "d-none"}, label: false  %>
            <%= f.input :document, input_html: { class: 'd-none', id: 'photo-input' }, label_html: { class: 'btn btn-outline-primary'}, label: 'Upload an additional document' %>
            <%= f.button :submit, "Attach document", class: "btn btn-outline-primary" %>
          <% end %>
          <% end %>
        <% end %>
      </div>
      <% if @application.document.attached? %>
    </div>
    <% end %>
  <div class="buttons-application">
    <div class="buttons-application-show">
      <% if @application.sent == false %>
      <%= link_to "", sent_application_path(@application), method: :patch, id: "delete-link", class: "hidden" %>
      <button id="sweet-alert-demo" class="btn btn-ghost">Submit your application</button>
      <%= link_to "Edit your application", edit_application_path, class: "btn btn-outline-primary" %>
      <% end %>
      <%= link_to "Go back to #{@application.startup.name}", startup_path(@application.startup.id), class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>