config/routes.rb
 Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'

  get 'dashboard', to: 'profiles#dashboard', as: :dashboard
  patch '/applications/:id/sent_application', to: 'applications#sent_application', as: :sent_application

  resources :startups, only: [ :index, :show ] do
    resources :applications, only: [ :new, :create ]
    resources :favorites, only: :create
  end


  resources :applications, only: [ :index, :show, :create, :edit, :update, :destroy ]
  resources :favorites, only: [ :index, :destroy ]
  resources :sectors, only: :index
  resources :profiles, only: [ :create, :edit, :update ]
end

app/models/startup.rb
class Startup < ApplicationRecord
  # for Cloudinary - in a later stage - depending if we get the API or not. If latter then we have to seed the logos ourselves
  has_one_attached :logo
  has_many :applications, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :startup_sectors, dependent: :destroy

  has_many :users, through: :favorites
  has_many :sectors, through: :startup_sectors

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_all_attributes,
    against: [ :name, :description, :address, :website, :email ],
    using: {
      tsearch: { prefix: true } # <-- now `startup in berlin` will return something!
    }
end

# line 16: add also :sector through startup_sectors

# associated_against: {
#       startup_sector: [ :id, :name ]
#     },

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

# GET /startups
  def index
    #it's taking from the user the sectors, just the id, and for each id is checking for the startup's matches
    if params[:search].present?
      @startups = Startup.search_by_all_attributes("%#{params[:search][:query]}%")
      Startup.joins(:startup_sectors).where(startup_sectors: {sector: Sector.find_by(name: params[:search][:query])}).each do |startup|
        @startups << startup
      end
    # we are checking two conditions: if the user is signed in and if the current user has any interests
    elsif user_signed_in? && current_user.user_sectors.any?
      @startups = Startup.joins(:startup_sectors).where(startup_sectors: {sector_id: current_user.sectors.pluck(:id)})
    else
      @startups = Startup.all
      # @startups = @startups.select { |startup| startup.sector_ids.include?(params[:sector_id].to_i) }
    end
  end

  def show
    @startup = Startup.find(params[:id])
    @favorite = Favorite.new
    @application = Application.new

    @markers = [
      {
        lat: @startup.latitude,
        lng: @startup.longitude
      }]
  end
end

app/views/startups/_card-startup-details.html.erb
<div class="container">
  <h1> @startup.name.capitalize</h1>
  <p> Details: @startup.description</p>
  <p>📍Address: @startup.address</p>
  <p> Website: @startup.website</p>
  <p> Email: @startup.email</p>
</div>

app/views/startups/_card-startup-index.html.erb
<div class="center">
  <div class="card green">
    <div class="additional">
      <div class="startup-card-index">
        <div class="sectors center">
          <% startup.sectors.each do |sector| %>
          <img src="<%= startup.logo_url %>" alt="Startup Missing Logo" class="startup-logo">
          <p id="sector-card-index"> <%= sector.name.capitalize %> </p>
        <% end %>
        </div>
      </div>
      <div class="more-info">
        <h1><%= name %></h1>
        <div class="coords">
          <span><i class="fas fa-map-marker-alt" style="color: white"></i></span>
          <span><%= address %></span>
        </div>
        <div class="coords">
          <span><i class="fas fa-envelope" style="color: white"></i></span>
          <span><%= email %></span>
        </div>
        <div class="coords">
          <span><i class="fas fa-external-link-alt" style="color: white"></i></span>
          <span><%= website %></span>
        </div>
      </div>
    </div>
    <div class="general">
      <h1><%= name %></h1>
      <p><%= truncate(description, length: 170) %></p>
      <span class="more"><strong><%= employees %></strong><i class="fas fa-users" style="color: gray; margin-left: 10px;"></i></span>
    </div>
  </div>
</div>

app/views/startups/index.html.erb
<div class="container" style= "margin-top: 30px">
  <% if user_signed_in? %>
  <div class="container box-card-index">
    <h1 style="font-size: 35px; color:#52A87C; text-align:center;"><strong>It's a match!</strong></h1>
    <p style="color: #52A87C; text-align:center; margin-top:-10px; margin-bottom: -5px;" >______________________________________</p>
    <!-- <h2 style="color:#50A87C; text-align:center; margin-bottom:-17px">Your chosen interests</h2> -->
    <div class="d-flex box-card-sectors">
    <% current_user.sectors.each do |sector| %>
    <div class="card-interests">
      <div class= "card-logo-interests">
        <i class="<%= sector.sector_icon_font %>"></i>
        <div>
          <h3><%= sector.name %></h3>
        </div>
      </div>
    </div>
    <% end %>
    </div>
    <div style="text-align:center; margin-top:-2px;"><%= link_to "Edit interests", sectors_path(query: current_user.sectors.pluck(:name)), class: "btn btn-outline-primary btn-sm" %></div>
  <!-- </div> -->
  <% end %>
  <div class="container box-card-index">
    <h3 style="text-align:left; margin-bottom: 40px; margin-left: 95px;">Here are <strong style="color:#52A87C"><%= @startups.count %> startups</strong> matching your chosen interests:</h3>
    <!-- <div> -->
    <div class="startup-cards">
      <%= simple_form_for :search, url: startups_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search startup" />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i>
        </button>
      </div>
      <% end %>
    </div>

      <% @startups.each do |startup| %>
        <div class="card-codepen position-relative">
          <%= link_to startup_path(startup) do %>
          <%= render 'startups/card-startup-index', startup: startup, name: startup.name.capitalize, address: startup.address.capitalize, email: startup.email, website: startup.website, description: startup.description.capitalize, employees: startup.employees, logo_url: startup.logo_url %>
          <% end %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/startups/show.html.erb
<% content_for :meta_title, "#{@startup.name}" %>
<div class="container d-flex showw" style= "height:100vh">
  <div class="container card-startup-details">
    <div class="container">
      <div class="d-flex">
        <h1 style="white-space: nowrap;"> <%= @startup.name %> </h1>
        <% @startup.sectors.each do |sector| %>
          <i class="<%= sector.sector_icon_font %> sector-icon", style="margin-left:20px"></i>
        <% end %>
        <% if user_signed_in? %>
          <%  user_favorite = @startup.favorites.where(user_id: current_user.id).first %>
          <% if user_favorite %>
            <%= link_to '<i class="fas fa-heart favorite-icon"></i>'.html_safe, favorite_path(user_favorite), method: :delete %>
          <% else %>
            <%= link_to '<i class="far fa-heart favorite-icon"></i>'.html_safe, startup_favorites_path(@startup), method: :post %>
          <% end %>
        <% end %>
      </div>
      <hr style="color:#52A87C; margin-bottom: 20px">
      <p> <%= @startup.description %> </p>
      <p style="margin-bottom:0px"><i class="fas fa-map-marker-alt" style="margin-right:15px"></i>   <%= @startup.address %> </p>
      <i class="fas fa-external-link-alt" style="margin-right:15px"></i> <a href="<%= @startup.website %>" style="color:#52A87C; font-size:large"> <%= @startup.website %> </a>
      <p style="margin-top: 5px"><i class="fas fa-envelope" style="margin-right:15px"></i> <%= @startup.email %> </p>
<!-- BUTTONS  -->

    <% if user_signed_in? && current_user.application_for(@startup) %>
        <%= link_to 'View application', application_path(current_user.application_for(@startup)), class: "btn btn-ghost" %>
    <% else %>
      <%= simple_form_for [@startup, @application] do |f| %>
        <%= hidden_field_tag "application[startup_id]", @startup.id %>
        <%= f.button :submit, class: "btn btn-ghost" %>
      <% end %>
    <% end %>

    <%= link_to "Back to all startups", startups_path, class: "btn btn-outline-primary btn-sm" %>

    </div>
  </div>
 <div class="container">
  <div class="col col-lg-12">
      <div id="map" class="z-depth-1-half map-container-6" style="height: 600px; margin-top:50px"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>